config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root 'homepage#index'
  resources :users, only: %i[index], path: 'authors', as: 'authors'
  resources :subscriptions, only: %i[create destroy]
  resources :feeds, only: [:index]
  resources :posts, only: %i[new index show create] do
    resources :comments, only: %i[new create index]
  end
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  ancestry   :string           not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_ancestry  (ancestry)
#  index_comments_on_post_id   (post_id)
#  index_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  has_ancestry

  belongs_to :user
  belongs_to :post

  validates :body, presence: { on: :create },
                   length: { maximum: Constants::Post::BODY_MAX_SIZE }
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ProtectedController
  before_action :set_post, only: %i[new create index]

  def index
    redirect_to post_path(@post)
  end

  def new
    @comment = @post.comments.new(parent_id: params[:parent_id])
  end

  def create
    @comment = @post.comments.new(comment_params.merge(user: current_user))

    if @comment.save
      redirect_to post_path(@post), notice: t('comments.comment_added')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_id)
  end
end

app/views/comments/_comment.haml
.comment.mt-2.shadow-sm
  .comment-body.bg-light.p-1.rounded.shadow-sm
    .d-flex.justify-content-between.align-items-center
      %strong= link_to comment.user.decorate.full_name, posts_path(user_id: comment.user_id), data: { turbo: false },
        class: 'link-dark link-offset-2 link-underline link-underline-opacity-0'
      %small.text-muted= l(comment.created_at, format: :short)
    %p.comment-body.ms-2= comment.body

    - from_reply_form ||= nil
    - unless from_reply_form
      .comment-actions.mt-2
        = link_to t('.reply'), new_post_comment_path(comment.post, parent_id: comment.id), class: 'btn btn-sm btn-link'

  - if children.any?
    .replies.mt-2.ms-4
      - children.each do |comment, children|
        = render partial: 'comments/comment', locals: { comment:, children: }

app/views/comments/new.haml
.p-5.mt-4.bg-light.rounded-3
  - if @comment.parent
    %h2.text-center.text-primary.page-title= t('.reply_to_comment')
    = render partial: 'comments/comment', locals: { comment: @comment.parent, children: [], from_reply_form: true }
  - else
    %h2.text-center.text-primary.page-title= t('.new_comment')
.mb-4
  .row
    .col-12
      = simple_form_for @comment, url: post_comments_path(@post), data: { turbo: false } do |f|
        .row.g-4.justify-content-md-center
          .col-8
            = f.input_field :body, as: :text, autocomplete: 'body', id: 'body', class: 'form-control body-input', placeholder: t('.enter_comment')
            = f.full_error :body, class: 'text-danger', id: 'body-error'
            = f.hidden_field :parent_id, value: @comment.parent_id
          .col-8.text-center
            = link_to t('.back'), :back, class: 'btn btn-primary back-link'
            = f.submit t('.save'), class: 'btn btn-primary mb-35 save-btn'