config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root 'homepage#index'
  resources :users, only: %i[index], path: 'authors', as: 'authors'
  resources :subscriptions, only: %i[create destroy]
  resources :feeds, only: [:index]
  resources :posts, only: %i[new index show create] do
    resources :comments, only: %i[new create index]
  end
end

app/views/partials/_flash_messages.haml
- flash.each do |name, msg|
  = content_tag :div, msg, id: "flash_#{name}", class: "container alert #{flash_class(name)}"

app/views/partials/_footer.haml
%footer.bg-light
  .container.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4
    .col-md-4.d-flex.align-items-center
      = link_to root_path, class: 'mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1 home-link' do
        = image_tag 'logo.png', size: '30'
        %span.mb-3.mb-md-0.text-muted= t('.company')
    %ul.nav.col-md-4.justify-content-end.list-unstyled.d-flex
      %li.ms-3
        = link_to '#', class: 'text-muted' do
          %i.bi.bi-twitter.fs-3.text-body
      %li.ms-3
        = link_to '#', class: 'text-muted' do
          %i.bi.bi-facebook.fs-3.text-body
      %li.ms-3
        = link_to '#', class: 'text-muted' do
          %i.bi.bi-instagram.fs-3.text-body

app/views/partials/_head.haml
%head
  %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }
  %title= t('.window_title')
  %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload'
  = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  = favicon_link_tag 'favicon.png', type: 'image/png'

app/views/partials/_header.haml
%header
  %nav.navbar.navbar-expand-lg.bg-light
    .container
      .navbar-header
        %a.navbar-brand{ href: '#' }= t('.site_title')
      #navbarNavDropdown.collapse.navbar-collapse.justify-content-end
        %ul.navbar-nav
          %li.nav-item
            = link_to t('.home_link'), root_path, class: 'nav-link active home-link'
          - if user_signed_in?
            %li.nav-item
              = link_to t('.feed'), feeds_path, class: 'nav-link active home-link'
            %li.nav-item
              = link_to t('.find_author'), authors_path(type: :all_authors), class: 'nav-link active home-link'
            %li.nav-item
              = link_to t('.new_post'), new_post_path, class: 'nav-link active home-link'
            %li.nav-item.dropdown
              = link_to current_user.first_name, '#',
                aria: { expanded: false, haspopup: true },
                data: { 'bs-toggle': 'dropdown' }, role: 'button',
                class: 'account-menu-button nav-link dropdown-toggle'
              %ul.dropdown-menu.account-menu
                %li= link_to t('.my_posts'), posts_path, class: 'appointments-link dropdown-item'
                %li.divider{ role: 'separator' }
                %li= link_to t('.my_subscriptions'), authors_path(type: :subscribed_to_users),
                  class: 'appointments-link dropdown-item'
                %li.divider{ role: 'separator' }
                %li= link_to t('.my_subscribers'), authors_path(type: :subscribers),
                  class: 'appointments-link dropdown-item'
                %li= link_to t('.logout'),
                  destroy_user_session_path, method: :delete,
                  class: 'logout-button dropdown-item', form_class: 'logout-form'
          - else
            %li.nav-item
              = link_to t('.login'), new_user_session_path, class: 'sign-up-link nav-link'
            %li.nav-item
              = link_to t('.sign_up'), new_user_registration_path, class: 'sign-up-link nav-link'