config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end

  root 'homepage#index'
  resources :users, only: %i[index], path: 'authors', as: 'authors'
  resources :subscriptions, only: %i[create destroy]
  resources :feeds, only: [:index]
  resources :posts, only: %i[new index show create] do
    resources :comments, only: %i[new create index]
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  validates :title, presence: { on: :create },
                    length: { maximum: Constants::Post::TITLE_MAX_SIZE }
  validates :body, presence: { on: :create },
                   length: { maximum: Constants::Post::BODY_MAX_SIZE }

  belongs_to :user
  has_many :comments, dependent: :destroy

  counter_culture :user
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ProtectedController
  def index
    @user = User.find_by(id: params[:user_id]) || current_user
    @pagy, posts = pagy(@user.posts, items: Constants::Shared::ITEMS_PER_PAGE)
    @posts = posts.decorate
  end

  def show
    @post = Post.find(params[:id]).decorate
    @comments = @post.comments.lazy_preload(:user).order(created_at: :asc).arrange
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/views/posts/_post.haml
%li.list-group-item.d-flex.justify-content-between.align-items-start.mb-2
  .post-details.text-start
    %h5= link_to post.title, post_path(post), class: 'text-primary'
    %p.text-muted= truncate(post.body, length: 100)

  .post-meta.text-end
    %div
      %span.badge.bg-secondary= post.author
      %span.badge.bg-info= l(post.created_at, format: :short)

app/views/posts/index.haml
.bg-light.py-5.my-2
  - if @user == current_user
    %h2.text-center.text-primary= t('.my_posts')
  - else
    %h2.text-center.text-primary= t('.posts_by', author: @user.decorate.full_name)
    .d-flex.justify-content-center.align-items-center.mt-2
      = link_to t('.back'), :back, class: 'btn btn-link back-link fs-5'
      - if subscribed_to?(@user)
        = button_to t('.unsubscribe'), subscription_path(@user), method: :delete, data: { turbo: false },
          class: 'btn btn-link text-danger fs-5'
      - else
        = button_to t('.subscribe'), subscriptions_path(id: @user.id), method: :post, data: { turbo: false },
          class: 'btn btn-link text-primary fs-5'
  .row.justify-content-md-center
    .col-8.text-center
      - if @posts.any?
        %ul.list-group
          = render @posts
      - else
        .alert.alert-warning.text-center
          = t('.no_posts_found')
    - if @pagy.pages > 1
      .col-10.justify-content-center.pagination.mt-4
        != pagy_bootstrap_nav @pagy

app/views/posts/new.haml
.p-5.mt-4.bg-light.rounded-3
  %h2.text-center.text-primary.page-title= t('.new_post')
.mb-4
  .row
    .col-12
      = simple_form_for @post, url: posts_path, data: { turbo: false } do |f|
        .row.g-4.justify-content-md-center
          .col-8
            = f.label :title, t('.enter_title'), class: 'form-label title-label'
            = f.input_field :title, as: :string, autocomplete: 'title',
              id: 'title', class: 'form-control title-input', placeholder: t('.enter_title_up_to')
            = f.full_error :title, class: 'text-danger', id: 'title-error'
          .col-8
            = f.label :body, t('.enter_body'), class: 'form-label body-label'
            = f.input_field :body, as: :text, autocomplete: 'body',
              id: 'body', class: 'form-control body-input', placeholder: t('.enter_body_up_to')
            = f.full_error :body, class: 'text-danger', id: 'body-error'
          .col-8.text-center
            = link_to t('.back'), :back, class: 'btn btn-primary back-link'
            = f.submit t('.save'), class: 'btn btn-primary mb-35 save-btn'

app/views/posts/show.haml
.p-5.mt-4.bg-light.rounded-3.shadow-sm
  .container
    %h1.text-center.text-primary= @post.title
    %h6.text-muted.text-center
      = t('.author')
      = link_to @post.author, posts_path(user_id: @post.user_id), data: { turbo: false },
        class: 'btn btn-link'
    %hr
    .mt-4
      %p= @post.body
    .mt-4.text-center
      = link_to t('.comment'), new_post_comment_path(@post), class: 'btn btn-warning'
      = link_to t('.back'), :back, class: 'btn btn-secondary'
.mt-5
  %h3.text-center.text-primary= t('.comments')
  - @comments.each do |comment, children|
    = render partial: 'comments/comment', locals: { comment:, children: }